### ISSUE TITLE
[CleanSheet] existing mylyn/bugzilla task => empty dialog, if opened in editor on eclipse starts => eclipse doesn't start

### ISSUE THREAD

**Issue by dex-ds** [fappel/xiliary#76]
Eclispe is unusable in that case.
Only a manually reset in
.metadata.plugins\org.eclipse.core.runtime.settings\org.eclipse.e4.ui.css.swt.theme.prefs
from
`themeid=com.codeaffine.eclipse.ui.swt.theme.clean-sheet10`
to (e.g.)
`themeid=org.eclipse.e4.ui.css.theme.e4_classic`
helps.

**Comment by dex-ds** [comment]
my workaround at this time disable this in clean-sheet-win.css
```
ScrolledForm {
  flat-scroll-bar: false;
```

**Comment by fappel** [comment]
Ouch, this sounds serious. Thanks for reporting the issue.

**Comment by abelhegedus** [comment]
I have the same issue, cannot use Mylyn with CleanSheet installed:

![clean-sheet-mylyn](https://cloud.githubusercontent.com/assets/716108/24108955/81e45000-0d8f-11e7-9dc0-994f34274aa9.png)

```
eclipse.buildId=4.7.0.I20161208-0830
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product

org.eclipse.ui
Error
Mon Mar 20 16:56:20 CET 2017
Unhandled event loop exception

java.lang.NullPointerException
	at org.eclipse.swt.widgets.ScrollBarAdapter.getSize(ScrollBarAdapter.java:32)
	at org.eclipse.mylyn.commons.ui.FillWidthLayout.calculateWidthHint(FillWidthLayout.java:142)
	at org.eclipse.mylyn.commons.ui.FillWidthLayout.calculateWidthHint(FillWidthLayout.java:123)
	at org.eclipse.mylyn.commons.ui.FillWidthLayout.calculateWidthHint(FillWidthLayout.java:123)
	at org.eclipse.mylyn.commons.ui.FillWidthLayout.calculateWidthHint(FillWidthLayout.java:123)
	at org.eclipse.mylyn.commons.ui.FillWidthLayout.calculateWidthHint(FillWidthLayout.java:123)
	at org.eclipse.mylyn.commons.ui.FillWidthLayout.calculateWidthHint(FillWidthLayout.java:123)
	at org.eclipse.mylyn.commons.ui.FillWidthLayout.calculateWidthHint(FillWidthLayout.java:110)
	at org.eclipse.mylyn.commons.ui.FillWidthLayout.computeSize(FillWidthLayout.java:156)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:215)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:663)
	at org.eclipse.ui.forms.widgets.LayoutComposite.computeSize(LayoutComposite.java:37)
	at org.eclipse.ui.forms.widgets.SizeCache.controlComputeSize(SizeCache.java:391)
	at org.eclipse.ui.forms.widgets.SizeCache.computeMinimumHeight(SizeCache.java:478)
	at org.eclipse.ui.forms.widgets.SizeCache.computeSize(SizeCache.java:200)
	at org.eclipse.ui.forms.widgets.ExpandableComposite$ExpandableLayout.computeSize(ExpandableComposite.java:472)
	at org.eclipse.ui.forms.widgets.ExpandableComposite.computeSize(ExpandableComposite.java:943)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:491)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:221)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:164)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:215)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:663)
	at org.eclipse.ui.forms.widgets.LayoutComposite.computeSize(LayoutComposite.java:37)
	at org.eclipse.ui.forms.widgets.SizeCache.controlComputeSize(SizeCache.java:391)
	at org.eclipse.ui.forms.widgets.SizeCache.computeMinimumWidth(SizeCache.java:430)
	at org.eclipse.ui.forms.widgets.SizeCache.computeSize(SizeCache.java:189)
	at org.eclipse.ui.forms.widgets.Form$FormLayout.computeSize(Form.java:143)
	at org.eclipse.ui.forms.widgets.Form.computeSize(Form.java:200)
	at org.eclipse.ui.forms.widgets.SizeCache.controlComputeSize(SizeCache.java:391)
	at org.eclipse.ui.forms.widgets.SizeCache.computeMinimumHeight(SizeCache.java:478)
	at org.eclipse.ui.forms.widgets.SizeCache.computeSize(SizeCache.java:200)
	at org.eclipse.ui.forms.widgets.SharedScrolledComposite.reflow(SharedScrolledComposite.java:183)
	at org.eclipse.ui.forms.widgets.SharedScrolledComposite.scheduleReflow(SharedScrolledComposite.java:229)
	at org.eclipse.ui.forms.widgets.SharedScrolledComposite.lambda$0(SharedScrolledComposite.java:64)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4431)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Control.WM_SIZE(Control.java:5498)
	at org.eclipse.swt.widgets.Scrollable.WM_SIZE(Scrollable.java:367)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1763)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4905)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5181)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2548)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5730)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4918)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5181)
	at org.eclipse.swt.internal.win32.OS.SetWindowPos(Native Method)
	at org.eclipse.swt.widgets.Widget.SetWindowPos(Widget.java:1482)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3290)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1079)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3251)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3247)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3323)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3319)
	at org.eclipse.swt.custom.CTabFolderLayout.layout(CTabFolderLayout.java:116)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1363)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1348)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:702)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:653)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:609)
	at org.eclipse.swt.custom.CTabFolder.runUpdate(CTabFolder.java:3839)
	at org.eclipse.swt.custom.CTabFolder.getItem(CTabFolder.java:930)
	at org.eclipse.swt.custom.CTabFolder._getToolTip(CTabFolder.java:3886)
	at org.eclipse.swt.custom.CTabFolder._setToolTipText(CTabFolder.java:3708)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1879)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:336)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4431)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4241)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1133)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:698)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

**Comment by fappel** [comment]
Thanks for providing the stacktrace. I was able to reproduce the problem in debug mode. The cause is a poorly designed class that does some complicated initializations during construction time. This triggers the scrollable adapter layout mechanism prematurely meaning before initialization of the adapter has been completed. Hence the NPE. That happens if you disregard the general advice and do other things than simple field assignments in constructors... well, well, well shame on me.

Unfortunately, it's very complicated and delicate to rework this part of the adapter mechanism. Although I have a large test suite for the stuff, given the complex context I wouldn't trust a rework without a lot of manual testing. For which I currently lack the time. Hence, I did a more pragmatic workaround and fixed the NPE by providing a (0,0) point as default value as long as the ScrollBarAdapter has not been initialized. With this in place, the Mylyn Bugzilla Task Editor opened up like a charm.

Currently, I'm waiting for the build to deploy a new version on the CI development repository. This might take a while since for unknown reasons the last tries ran into socket timeouts while loading artifacts via maven-tycho. Once finished, the version could be installed using the repository located at http://fappel.github.io/xiliary/development/. A confirmation of the fix would be nice before actually releasing the version into the great wide open, meaning the main branch...

**Comment by abelhegedus** [comment]
Sounds great! Thanks for the fix, I will test it when it's available and report back.

**Comment by fappel** [comment]
Thanks, the development P2 repository has now been updated.

**Comment by abelhegedus** [comment]
I just saw the new version appear on the development update site. It has fixed the problem for me! Thanks 👍 🏆
