### ISSUE TITLE
NPE in FlatScrollBar#setBackground

### ISSUE THREAD

**Issue by kthoms** [fappel/xiliary#86]
The following NPE is reported frequently to Eclipse's Error Reporting System:

```
Bundle: org.eclipse.e4.ui.css.swt.theme 0.11.0.v20170312-2302
Message:
Exception:
java.lang.NullPointerException: null
    at com.codeaffine.eclipse.swt.widget.scrollbar.FlatScrollBar.setBackground(FlatScrollBar.java:237)
    at org.eclipse.e4.ui.css.swt.helpers.CSSSWTColorHelper.setBackground(CSSSWTColorHelper.java:357)
    at org.eclipse.e4.ui.css.swt.properties.css2.CSSPropertyBackgroundSWTHandler.applyCSSPropertyBackgroundColor(CSSPropertyBackgroundSWTHandler.java:77)
    at org.eclipse.e4.ui.css.core.dom.properties.css2.AbstractCSSPropertyBackgroundHandler.applyCSSProperty(AbstractCSSPropertyBackgroundHandler.java:35)
    at org.eclipse.e4.ui.css.swt.properties.css2.CSSPropertyBackgroundSWTHandler.applyCSSProperty(CSSPropertyBackgroundSWTHandler.java:43)
    at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyCSSProperty(AbstractCSSEngine.java:766)
    at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyleDeclaration(AbstractCSSEngine.java:552)
    at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:426)
    at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:367)
    at org.eclipse.e4.ui.css.swt.engine.CSSSWTEngineImpl.applyStyles(CSSSWTEngineImpl.java:29)
    at org.eclipse.e4.ui.css.swt.engine.CSSSWTApplyStylesListener$1.handleEvent(CSSSWTApplyStylesListener.java:32)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4420)
    at org.eclipse.swt.widgets.Display.runSkin(Display.java:4321)
    at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1361)
    at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1774)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4918)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
    at org.eclipse.swt.internal.win32.OS.DefWindowProcW(OS.java:-2)
    at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2555)
    at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
    at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5743)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4931)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
    at org.eclipse.swt.internal.win32.OS.SetWindowPos(OS.java:-2)
    at org.eclipse.swt.widgets.Widget.SetWindowPos(Widget.java:1482)
    at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3304)
    at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1079)
    at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3265)
    at org.eclipse.swt.widgets.Control.setSizeInPixels(Control.java:3829)
    at org.eclipse.swt.widgets.Control.setSize(Control.java:3824)
    at com.codeaffine.eclipse.swt.widget.scrollbar.Direction$2.setDefaultSize(Direction.java:116)
    at com.codeaffine.eclipse.swt.widget.scrollbar.FlatScrollBar.(FlatScrollBar.java:71)
    at com.codeaffine.eclipse.swt.widget.scrollbar.FlatScrollBar.(FlatScrollBar.java:57)
    at com.codeaffine.eclipse.swt.widget.scrollbar.FlatScrollBarsProvider.createScrollBars(FlatScrollBarsProvider.java:23)
    at org.eclipse.swt.custom.ScrolledComposite.createScrollBar(ScrolledComposite.java:842)
    at org.eclipse.swt.custom.ScrolledComposite.(ScrolledComposite.java:163)
    at org.eclipse.equinox.internal.p2.ui.discovery.util.ControlListViewer.(ControlListViewer.java:50)
    at org.eclipse.equinox.internal.p2.ui.discovery.wizards.CatalogViewer$3.(CatalogViewer.java:329)
    at org.eclipse.equinox.internal.p2.ui.discovery.wizards.CatalogViewer.doCreateViewer(CatalogViewer.java:329)
    at org.eclipse.epp.internal.mpc.ui.wizards.MarketplaceViewer.doCreateViewer(MarketplaceViewer.java:917)
    at org.eclipse.equinox.internal.p2.ui.discovery.util.FilteredViewer.createControl(FilteredViewer.java:80)
    at org.eclipse.epp.internal.mpc.ui.wizards.MarketplacePage.doCreateViewer(MarketplacePage.java:725)
    at org.eclipse.equinox.internal.p2.ui.discovery.wizards.CatalogPage.createControl(CatalogPage.java:52)
    at org.eclipse.epp.internal.mpc.ui.wizards.MarketplacePage.createControl(MarketplacePage.java:184)
    at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:176)
    at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:688)
    at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:580)
    at org.eclipse.jface.window.Window.create(Window.java:426)
    at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1096)
    at org.eclipse.jface.window.Window.open(Window.java:783)
    at org.eclipse.epp.internal.mpc.ui.commands.AbstractMarketplaceWizardCommand.openWizardDialog(AbstractMarketplaceWizardCommand.java:144)
    at org.eclipse.epp.internal.mpc.ui.commands.AbstractMarketplaceWizardCommand.execute(AbstractMarketplaceWizardCommand.java:71)
    at org.eclipse.epp.mpc.ui.MarketplaceUrlHandler.triggerInstall(MarketplaceUrlHandler.java:222)
    at org.eclipse.epp.internal.mpc.ui.wizards.MarketplaceDropAdapter.proceedInstallation(MarketplaceDropAdapter.java:168)
    at org.eclipse.epp.internal.mpc.ui.wizards.MarketplaceDropAdapter$MarketplaceDropTargetListener$1.run(MarketplaceDropAdapter.java:295)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
    at org.eclipse.jface.window.Window.open(Window.java:794)
    at org.eclipse.epp.internal.mpc.ui.commands.AbstractMarketplaceWizardCommand.openWizardDialog(AbstractMarketplaceWizardCommand.java:144)
    at org.eclipse.epp.internal.mpc.ui.commands.AbstractMarketplaceWizardCommand.execute(AbstractMarketplaceWizardCommand.java:71)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
    at sun.reflect.GeneratedMethodAccessor100.invoke(null:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
    at java.lang.reflect.Method.invoke(null:-1)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
    at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
    at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
    at java.lang.reflect.Method.invoke(null:-1)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

Eclipse version is 4.7.2.

Internal reference: https://dev.eclipse.org/recommenders/committers/aeri/v2/#!/problems/5922b6d6e4b00e98f02d8444

**Comment by fappel** [comment]
Thanks for reporting this, I will have a look ASAP.

**Comment by fappel** [comment]
Hi, it took me a while, sorry. But I'm not sure I can do anything about it. FlatScrollBar.java:237 as mentioned in the stacktrace above is not an instruction line. 238 would be, but 237 just isn't. But even if 238 is the place to look at: the field accessed at that line number gets set during construction time and is marked as final. It seems to me that there is no regular way to make the NPE happen.

There are some very few parts in the overall codebase that make use of Unsafe to construct native scrollbars, but - if I remember it correctly - never to create FlatScrollBar instances. Last relevant changes to the code in question were over four years ago according to git, the last changes to the file about three and a half years - updating the copy right line. Again, I can't think of a way how the code can cause the stacktrace above. I have been known to be mistaken, however...

Nevertheless, the stacktrace exists. So how can this happen? There are forks of the repository around and I am aware of a quite popular Eclipse theme that allegedly uses Code Affine FlatScrollBars under the hood. From what I've heard the codebase has been changed a bit. Hence, it might be possible that the bug was introduced by such changes. If the latter would be the case, there's no chance for Code Affine to fix something.

Because of this considerations I will close this issue for now. Feel free to reopen, if there is evidence that I've overlooked something and that explains how the mysterious line number can happen. Would be interesting to know for sure. Thank's again for reporting and sorry that I don't have a solution to provide.
